import type { IntakeData } from './types';

export const DEMO_INTAKE_DATA: IntakeData = {
  petitioner: {
    family_name: "Meh",
    given_name: "Kho",
    middle_name: "",
    ssn: "359-83-1756",
    other_names: "N/A",
    city_of_birth: "Thailand",
    country_of_birth: "Thailand",
    date_of_birth: "06/03/1998",
    sex: "F",
    ethnicity: "Not Hispanic or Latino",
    race: "Asian",
    height_feet: "5",
    height_inches: "3",
    weight_lbs: "155",
    eye_color: "Brown",
    hair_color: "Black",
    mailing_address: {
      street: "1300 Nassau Ave",
      apt_ste_flr: "Apt",
      unit_number: "B",
      city: "Owensboro",
      state: "KY",
      zip: "42301",
      country: "United States",
    },
    physical_same_as_mailing: true,
    address_history: [
      {
        street: "2321 Homestead Point",
        city: "Owensboro",
        state: "KY",
        zip: "42301",
        country: "United States",
        date_from: "09/01/2019",
        date_to: "",
      },
    ],
    times_married: "1",
    marital_status: "Married",
    date_of_marriage: "09/20/2025",
    marriage_city: "Beaver Dam",
    marriage_state: "KY",
    marriage_country: "United States",
    spouse_family_name: "Cardona Hernandez",
    spouse_given_name: "Geovany",
    spouse_middle_name: "Estuardo",
    parent1_family_name: "Reh",
    parent1_given_name: "Nga",
    parent1_middle_name: "",
    parent1_sex: "M",
    parent1_dob: "",
    parent1_country_of_birth: "Myanmar",
    parent1_city_of_residence: "",
    parent1_country_of_residence: "United States",
    parent2_family_name: "Meu",
    parent2_given_name: "Hseh",
    parent2_middle_name: "",
    parent2_sex: "F",
    parent2_dob: "",
    parent2_country_of_birth: "Myanmar",
    parent2_city_of_residence: "",
    parent2_country_of_residence: "United States",
    immigration_status: "US Citizen",
    citizenship_acquired_through: "",
    employer_name: "Tracco Total Packaging, LLC",
    employer_street: "901 Leitchfield Rd",
    employer_city: "Owensboro",
    employer_state: "KY",
    employer_zip: "42303",
    employer_country: "United States",
    occupation: "",
    employment_date_from: "02/26/2020",
    employment_date_to: "PRESENT",
    previously_filed_petition: "No",
    phone: "",
    email: "",
  },
  beneficiary: {
    family_name: "Cardona Hernandez",
    given_name: "Geovany",
    middle_name: "Estuardo",
    ssn: "842-77-9175",
    other_names: "",
    city_of_birth: "San Sebastian Huehuetenango",
    country_of_birth: "Guatemala",
    date_of_birth: "11/02/2002",
    sex: "M",
    current_address: {
      street: "1300 Nassau Ave",
      apt_ste_flr: "Apt",
      unit_number: "B",
      city: "Owensboro",
      state: "KY",
      zip: "42301",
      country: "United States",
    },
    phone: "804-997-6819",
    mobile_phone: "",
    email: "",
    times_married: "1",
    marital_status: "Married",
    date_of_marriage: "09/20/2025",
    marriage_city: "Beaver Dam",
    marriage_state: "KY",
    marriage_country: "United States",
    previous_spouses: "N/A",
    children: "None",
    petition_filed_before: "No",
    ever_in_us: "Yes",
    class_of_admission: "Asylum",
    date_of_arrival: "05/18/2019",
    authorized_stay_expiration: "",
    in_immigration_proceedings: "Yes",
    proceedings_type: "Removal",
    proceedings_city: "",
    proceedings_state: "",
    proceedings_date: "",
    address_history: [
      {
        street: "1300 Nassau Ave Apt B",
        city: "Owensboro",
        state: "KY",
        zip: "42301",
        country: "United States",
        date_from: "05/28/2022",
        date_to: "",
      },
      {
        street: "704 Walnut St",
        city: "Owensboro",
        state: "KY",
        zip: "42301",
        country: "United States",
        date_from: "07/21/2020",
        date_to: "",
      },
    ],
    last_address_outside_us: {
      street: "",
      city: "",
      province: "",
      country: "Guatemala",
    },
    parent1_family_name: "Cardona Sales",
    parent1_given_name: "Augusto",
    parent1_middle_name: "",
    parent1_dob: "10/17/1982",
    parent1_city_of_birth: "San Sebastian Huehuetenango",
    parent1_country_of_birth: "Guatemala",
    parent1_current_city: "",
    parent1_current_country: "Guatemala",
    parent2_family_name: "Hernandez Perez",
    parent2_given_name: "Isabel",
    parent2_middle_name: "",
    parent2_dob: "11/15/1981",
    parent2_city_of_birth: "San Sebastian Huehuetenango",
    parent2_country_of_birth: "Guatemala",
    parent2_current_city: "",
    parent2_current_country: "United States",
    employer_name: "Tracco-Total Packaging, LLC",
    employer_street: "901 Leitchfield Rd",
    employer_city: "Owensboro",
    employer_state: "KY",
    employer_zip: "42303",
    employer_country: "United States",
    occupation: "",
    employment_date_from: "01/20/2020",
    i94_number: "",
    passport_number: "",
    travel_doc_number: "",
    passport_country: "",
    passport_expiration: "",
  },
  relationship: "Spouse",
};
